# Generated by Django 4.0.3 on 2022-04-03 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeDaConfiguracao', models.CharField(max_length=100)),
                ('navBarCor', models.CharField(max_length=7)),
                ('tituloPag', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Configurações',
            },
        ),
        migrations.DeleteModel(
            name='Cor',
        ),
    ]
