# Generated by Django 4.0.3 on 2022-04-04 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_config_delete_cor'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='textNavBarCor',
            field=models.CharField(default=None, max_length=7),
            preserve_default=False,
        ),
    ]
