# Generated by Django 4.0.3 on 2022-04-04 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_config_textnavbarcor'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='contatoCor',
            field=models.CharField(default=None, max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='programacaoCor',
            field=models.CharField(default=None, max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='sobreOEventoCor',
            field=models.CharField(default=None, max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='textContatoCor',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='textProgramacaoCor',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='textSobreOEventoCor',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
