# Generated by Django 4.0.3 on 2022-04-04 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_config_contatocor_config_programacaocor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config',
            old_name='programacaoCor',
            new_name='programacaoEventoCor',
        ),
        migrations.RenameField(
            model_name='config',
            old_name='sobreOEventoCor',
            new_name='sobreEventoCor',
        ),
        migrations.RenameField(
            model_name='config',
            old_name='textProgramacaoCor',
            new_name='textProgramacaoEventoCor',
        ),
    ]
